server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5433/E_Commerence_DB
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- Redis Configuration ---
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=myredispassword

# --- Mail Configuration ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=valorant.vabeen@gmail.com
spring.mail.password=ljufcjfrttvlwfab
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


jwt.secret=++WwLhGs62vGtFlURYfoehTuE54hfi5AJcIO+WOQaaM=

# --- Stripe ---
stripe.secretKey=sk_test_51T0kR5A0UdJcCTK68l2S9y2ykXaxDK9CrmHGd4trLiMbKlwmO7PuMZUtM5kcpABguiqJmNlDGr3LFENWi410ANjC00rJ9mOnw7

# --- Cloudinary ---
cloudinary.cloud_name=dpi367qf8
cloudinary.api_key=439547882448746
cloudinary.api_secret=W_R2q7_ZhrkBtwfiG9BqOvM-PI

# --- Custom App Configs ---
app.base-url=http://localhost:8080
payment.session.ttl.minutes=60
payment.expire-check-cron=0 */1 * * * *

# --- OAuth2 ---
spring.security.oauth2.client.registration.google.client-id=placeholder
spring.security.oauth2.client.registration.google.client-secret=placeholder
spring.security.oauth2.client.registration.github.client-id=placeholder
spring.security.oauth2.client.registration.github.client-secret=placeholder